src/invoice_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("invoices.urls", namespace="invoices"))
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Invoices admin system"
admin.site.index_title = "Management"

src/invoices/urls.py
from django.urls import path
from .views import *



app_name = "invoices"

urlpatterns = [
    path("", InvoiceListView.as_view(), name="main"),
    path("new/", InvoiceFormView.as_view(), name="create"),
    # path('<pk>/', SimpleView.as_view(), name="detail"),
    path('<pk>/update/', InvoiceUpdateView.as_view(), name="update"),
    path('<pk>/closed/', CloseInvoiceView.as_view(), name="closed"),
    path('<pk>/', AddPositionsFormView.as_view(), name="detail"),
    path('<pk>/delete/<int:position_pk>/', InvoicePositionDeleteView.as_view(), name="delete"),
    path('<pk>/pdf/', invoice_pdf_view, name="pdf")
]

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- for icon png -->
    <link rel="shortcut icon" type="image/png" href="{% static 'venom.png' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'style.css' %}" /> {% block scripts %} {% endblock scripts %}

    <title>Invoice app | {% block title %} {% endblock title %}</title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container mt-3">
        {% block content %} {% endblock content %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>

</html>

src/templates/navbar.html
<nav class="navbar navbar-dark bg-primary">
    <div class="container">
        <a href="{% url 'invoices:main' %}" class="navbar-brand">Invoice app</a>
        <a href="{% url 'invoices:create' %}" class="btn btn-outline-light">+ New</a>
    </div>
</nav>