src/invoice_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("invoices.urls", namespace="invoices"))
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Invoices admin system"
admin.site.index_title = "Management"

src/invoices/urls.py
from django.urls import path
from .views import *



app_name = "invoices"

urlpatterns = [
    path("", InvoiceListView.as_view(), name="main"),
    path("new/", InvoiceFormView.as_view(), name="create"),
    # path('<pk>/', SimpleView.as_view(), name="detail"),
    path('<pk>/update/', InvoiceUpdateView.as_view(), name="update"),
    path('<pk>/closed/', CloseInvoiceView.as_view(), name="closed"),
    path('<pk>/', AddPositionsFormView.as_view(), name="detail"),
    path('<pk>/delete/<int:position_pk>/', InvoicePositionDeleteView.as_view(), name="delete"),
    path('<pk>/pdf/', invoice_pdf_view, name="pdf")
]

src/invoices/models.py
from django.db import models
from profiles.models import Profile
from receivers.models import Receiver


class Tag(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name


class Invoice(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    receiver = models.ForeignKey(Receiver, on_delete=models.CASCADE) 
    number = models.CharField(max_length=150)
    completion_date = models.DateField()
    issue_date = models.DateField()
    payment_day = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    # if closed - hide add positions and unable adding new once
    closed = models.BooleanField(default=False)
    # we add tag only for educational purposes
    tags = models.ManyToManyField(Tag, blank=True)
    
    def __str__(self):
        return f'invoice number: {self.number}, pk: {self.pk}'
    
    @property
    def tags(self):
        return self.tags.all()
    
    @property
    def positions(self):
        return self.position_set.all()
    
    @property
    def total_amount(self):
        total = 0
        qs = self.positions
        for pos in qs:
            total += pos.amount
        return total

src/invoices/forms.py
from django import forms
from .models import Invoice
from django.core.exceptions import ValidationError



class InvoiceForm(forms.ModelForm):
    completion_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}), label='дата підписання')
    issue_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}), label='дата отримання замовлення')
    payment_day = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}), label='дата оплати')
    class Meta:
        model = Invoice
        fields = ('receiver', 'number', 'completion_date', 'issue_date', 'payment_day')
        
        labels = {
            'receiver':'отримувач',
            'number': 'номер договору',
        }
        
        
    def clean_number(self):
        number = self.cleaned_data.get('number')
        if len(number) < 10:
            raise ValidationError('Занадто короткий номер договору')
        else:
            return number
        

src/invoices/views.py
from django.shortcuts import render, get_object_or_404
from .models import Invoice, Profile
from django.views.generic import ListView, FormView, DetailView, UpdateView, RedirectView, DeleteView
from profiles.models import Profile
from .forms import InvoiceForm
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from positions.forms import PositionForm
from positions.models import Position
from .mixins import InvoiceClosedMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from xhtml2pdf import pisa
from django.contrib.staticfiles import finders
from django.http import HttpResponse
from django.template.loader import get_template

# Create your views here.
class InvoiceListView(LoginRequiredMixin, ListView):
    model = Invoice
    paginate_by = 3
    template_name = 'invoices/main.html'# template_name by default invoice_list for model name
    context_object_name = 'qs'# object_list by defoult
    def get_queryset(self):
        # profile = Profile.objects.get(user=self.request.user)
        profile = get_object_or_404(Profile, user=self.request.user)
        # qs = Invoice.objects.filter(profile=profile).order_by('-created')
        # return qs
        return super().get_queryset().filter(profile=profile).order_by('-created')
    
    
class InvoiceFormView(LoginRequiredMixin, FormView):
    template_name = 'invoices/create.html'
    form_class = InvoiceForm
    # success_url = reverse_lazy("invoices:main")
    i_instance = None
    
    
    def form_valid(self, form):
        # add profile to forms
        profile = Profile.objects.get(user=self.request.user)
        instance = form.save(commit=False)
        instance.profile = profile
        form.save()
        self.i_instance = instance
        
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('invoices:detail', kwargs={'pk':self.i_instance.pk})
    
    
# class SimpleView(TemplateView):
#     template_name = "invoices/simple.html"

# class SimpleView(DetailView):
#     template_name = "invoices/simple.html"
#     model = Invoice
    
    
class AddPositionsFormView(LoginRequiredMixin, FormView):
    template_name = "invoices/detail.html"
    form_class = PositionForm
    
    def get_success_url(self):
        return self.request.path
    
    def form_valid(self, form):
        invoice_pk = self.kwargs.get('pk')
        invoice_obj = Invoice.objects.get(pk=invoice_pk)
        instance = form.save(commit=False)
        instance.invoice = invoice_obj
        form.save()
        messages.info(self.request, f"successfully added {instance.title}")
        
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        invoice_obj = Invoice.objects.get(pk=self.kwargs.get('pk'))
        qs = invoice_obj.positions
        context['obj'] = invoice_obj
        context['qs'] = qs
        
        return context
    
    
    
class InvoiceUpdateView(LoginRequiredMixin, InvoiceClosedMixin, UpdateView):
    template_name = "invoices/update.html"
    model = Invoice
    form_class = InvoiceForm
    success_url = reverse_lazy("invoices:main")
    
    def form_valid(self, form):
        instance = form.save()
        messages.info(self.request, f"Successfully updated invoice - {instance.number}")
        return super().form_valid(form)
    
    
class CloseInvoiceView(LoginRequiredMixin, RedirectView):
    pattern_name = "invoices:detail"
    
    def get_redirect_url(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Invoice.objects.get(pk=pk)
        obj.closed = True
        obj.save()
        
        return super().get_redirect_url(*args, **kwargs)
    
    
class InvoicePositionDeleteView(LoginRequiredMixin, InvoiceClosedMixin, DeleteView):
    model = Position
    template_name = "invoices/confirm_delete.html"
    
    # path <pk>/delete/<position_pk>
    def get_object(self):
        pk = self.kwargs.get('position_pk')
        obj = Position.objects.get(pk=pk)
        return obj
    
    def get_success_url(self):
        messages.info(self.request, f"successfully deleted position {self.object.title}")
        return reverse('invoices:detail', kwargs={'pk':self.object.invoice.id})
    
@login_required
def invoice_pdf_view(request, **kwargs):
    
    pk = kwargs.get('pk')
    obj = Invoice.objects.get(pk=pk)
    
    logo_result = finders.find('img/logo.png')
    font_result = finders.find('fonts/Lato-Regular.ttf')
    # show search location result
    searched_locations = finders.searched_locations
    print(searched_locations)
    
    template_path = 'invoices/pdf.html'
    context = {
        'object': obj,
        'static': {
            'font': font_result,
            'logo': logo_result,
        },
    }
    # Create a django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="invoice.pdf"'
    # find the template and render it
    template = get_template(template_path)
    html = template.render(context)
    
    # create pdf
    pisa_status = pisa.CreatePDF(html.encode('utf-8'), dest=response, encoding='utf-8')
    
    # if case of error
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>'+ html + '</pre>')
    return response
 
 
        

src/invoices/templates/invoices/confirm_delete.html
{% extends 'base.html' %}


{% block title %}Delete position{% endblock title %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <p>are you sure want to delete <b>{{object.title}}?</b></p>
        <button type="submit" class="btn btn-primary">Yes</button>
    </form>
{% endblock content %}

src/invoices/templates/invoices/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create{% endblock title %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{form | crispy}}
    <button class="btn btn-primary mt-3" type="submitte">Create</button> 
</form>
{% endblock content %}

src/invoices/templates/invoices/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}Detail{% endblock title %}

{% block content %}

  <div class="modal fade" id="AddPositionsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add positions</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary mt-3">save</button>
            </form>
        </div>
     
      </div>
    </div>
  </div>

  <div class="modal fade" id="CloseInvoiceModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Ви впевнені що хочете закрити цей договір(Invoice)?
        </div>
        <div class="modal-footer">
          <a href="{% url 'invoices:closed' obj.pk %}" class="btn btn-secondary">Close</a>
        </div>
      </div>
    </div>
  </div>

  <div>
    {% if not obj.closed %}
    
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#AddPositionsModal">
            + add positions
        </button>
        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#CloseInvoiceModal">
            close
        </button>
    {% else %}
        <a href="{% url 'invoices:pdf' obj.pk %}" class="btn btn-danger">PDF</a>
    {% endif %}
  </div>

{% if messages %}
    {% for message in messages  %}
        {% if message.tags == "info" %}
            <div class="alert alert-primary mt-2">
                {{message}}
            </div>
        {% endif %}
    
    {% endfor %}

{% endif %}
<div class="mt-3">
    <h4>Receiver: {{obj.receiver.name}}</h4>
    <hr>
    <h3>Positions</h3>

{% if qs %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for item in qs  %}
                
                <tr style="vertical-align: middle;">
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{item.title}}</td>
                    <td>{{item.description}}</td>
                    <td>${{item.amount}}</td>
                
                    <td>
                        {% if not obj.closed %}
                            <a href="{% url 'invoices:delete' obj.pk item.pk %}" class="btn btn-danger">X</a>
                        {% else %}
                        closed
                        {% endif %}
                        
                    </td>
                
                </tr>
                {% endfor %}
         
            </tbody>
        </table>
        <div class="mt-2 text-end">
            <h2>Total amount: ${{obj.total_amount}}</h2>
        </div>
{% else %}
    <hr>
    <h5>Positions no added...</h5>
{% endif %}

</div>


{% endblock content %}

src/invoices/templates/invoices/main.html
{% extends 'base.html' %}
{% block title %}home{% endblock title %}
{% block content %}
{% if messages %}
    {% for message in messages  %}
        {% if message.tags == "info" %}
            <div class="alert alert-primary mt-2">
                {{message}}
            </div>
        {% endif %}
    
    {% endfor %}

{% endif %}

{% if qs %}
    {% for obj in qs %}
    <div class="card mb-2" style="width:100%">
        <div class="card-body">
            <h5 class="card-title">{{obj.number}} - {{obj.receiver.name}}</h5>
            <div class="card-text">completion date: {{obj.completion_date}}</div>
            <div class="text-muted">amount: ${{obj.total_amount}}</div>
            <div class="mt-2">
                <a href="{% url 'invoices:detail' obj.pk %}" class="btn btn-primary">Details</a>
                {% if not obj.closed %}
                    <a href="{% url 'invoices:update' obj.pk %}" class="btn btn-info">Update</a>
                {% endif %}
                
            </div>
        </div>

    </div>


    {% endfor %}
{% else %}
    <h3>No invoices created...</h3>
{% endif %}

{% if is_paginated %}
    <nav aria-label="invoice pagination">
        <ul class="pagination">
        <li class="page-item {% if page_obj.has_previous %} {% else %} disabled  {% endif %}">
            <a {% if page_obj.has_previous %}
                href="?page={{ page_obj.previous_page_number }}"
            {% endif %}
            class="page-link" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
        {% for i in paginator.page_range %}
            <li class="page-item {% if page_obj.number == i %} active{% endif %}">
                <a class="page-link" href="?page={{i}}">{{i}}</a>
            </li>
        {% endfor %}

        
        <li class="page-item {% if page_obj.has_next %} {% else %} disabled  {% endif %}">
            <a {% if page_obj.has_next %}
            href="?page={{ page_obj.next_page_number }}"
            {% endif %} class="page-link">Next</a>
        </li>
        </ul>
    </nav>
{% endif %}

{% endblock content %}

src/invoices/templates/invoices/pdf.html
<!DOCTYPE html>
<html>
<head>
    <title>Invoice PDF</title>
    <meta http-equiv="Content-Type" content="text/html; charset='utf-8"/>
        <style>
            @page {
                size: a4 portrait;
                margin: 2cm;
            }
            {% comment %} @font-face {
                font-family: 'Lato';
                src: url({{static.font}});
            } {% endcomment %}
            * {
                font-family: 'Lato';
                font-size: 12px; 
            }

            table {
                border-collapse: collapse;
                border: 1px solid #e8e8e8;
                padding: 5px;
            }
        </style>
</head>
<body>
<section id="header-section">
    <table style="width: 100%; border: 0px">
        <tr>
            <th style="text-align:left; width:25%">
                <img src="{{static.logo}}" width="150">
            </th>
            <th style="text-align: right;">
                <br>
                <div style="font: size 18px;">Invoice number {{object.number}}</div>
                Completion_date: {{object.completion_date}}<br>
                Issue_date: {{object.issue_date}}<br>
                Payment_day: {{object.payment_day}}<br>
                <div>Account number: {{object.profile.account_number}}</div>
            </th>
        </tr>
    </table>
    <hr>
    <br>
    <table style="width: 100%;">
            <th style="text-align:left;">
                <div style="font-size: 15px;">Seller</div>
                {{object.profile.company_name}}<br>
            </th>
            <th style="text-align:left;">
                <div style="font-size: 15px;">Receiver</div>
                {{object.receiver.name}}<br>
                {{object.receiver.address}}<br>
                {{object.receiver.website}}
            </th>  
    </table>
</section>
<br>

<section id="data-section">
    {% if object.positions %}
        <h3>Positions</h3>
        <table style="width: 100%;">
            <tr style="background-color: #e8e8e8;">
                <th style="text-align:left; width:5%;">#</th>
                <th style="text-align:left;">Title</th>
                <th style="text-align:left;">Description</th>
                <th style="text-align:left;">Amount</th>
            </tr>
            {% for position in object.positions %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{position.title}}</td>
                    <td>{{position.description}}</td>
                    <td>${{position.amount}}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h3>No positions added</h3>
    {% endif %}
    <div style="font-size: 15px; margin-top: 10px; text-align:right">Total amount: ${{object.total_amount}}</div>
</section>
    
</body>
</html>

src/invoices/templates/invoices/simple.html
{% extends 'base.html' %}

{% block title %}add position{% endblock title %}

{% block content %}
Chose Position to add
{% endblock content %}

src/invoices/templates/invoices/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update{% endblock title %}
{% block content %}



<form action="" method="POST">
    {% csrf_token %}
    {{form | crispy}}
    <button class="btn btn-primary mt-2" type="submitte">Update</button> 
</form>

{% endblock content %}